language: c++
sudo: required

compiler:
  - gcc
  
python:
  - "2.7"

install:
  - sudo pip install lizard -q # Cyclomatic Complexity Check Tool

addons:
  apt:
    packages:
      - arm-none-eabi
      - cmake
      - valgrind

before_script:
  - arm-none-eabi-arm --version
  - gcc --version

script: ./configure.sh && ./test.sh
